### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by kingvuplus** [seife/meta-su980#1]
hellow  

i have added meta-su980 To OE-alliance ore for build Other enigma2 to Golden media Hypercub

the build is Ok but i have got this Error 

ERROR: Function failed: do_configure (log file is located at /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work/su980-oe-linux-gnueabi/linux-su980/2.6.34-r0/temp/log.do_configure.450)
ERROR: Logfile of failure stored in: /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work/su980-oe-linux-gnueabi/linux-su980/2.6.34-r0/temp/log.do_configure.450
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| NOTE: /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work/su980-oe-linux-gnueabi/linux-su980/2.6.34-r0/defconfig-su980 present, installing to /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work-shared/su980/kernel-source/.config
| NOTE: make oldconfig
| make: **\* No rule to make target `oldconfig'.  Stop.
| ERROR: oe_runmake failed
| WARNING: /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work/su980-oe-linux-gnueabi/linux-su980/2.6.34-r0/temp/run.do_configure.450:1 exit 1 from
|   exit 1
| ERROR: Function failed: do_configure (log file is located at /home/sodo/Bureau/fed/build-enviroment/builds/openatv/release/su980/tmp/work/su980-oe-linux-gnueabi/linux-su980/2.6.34-r0/temp/log.do_configure.450)
ERROR: Task 81 (/home/sodo/Bureau/fed/build-enviroment/meta-oe-alliance/meta-brands/meta-su980/recipes-linux/linux/linux-su980_2.6.34.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1407 tasks of which 1404 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/sodo/Bureau/fed/build-enviroment/meta-oe-alliance/meta-brands/meta-su980/recipes-linux/linux/linux-su980_2.6.34.bb, do_configure
Summary: There were 75 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: **\* [image] Error 1

any help To fix that please

**Comment by seife** [comment]
This has nothing to do with this repository here.
