### ISSUE TITLE
For what this is for?

### ISSUE THREAD

**Issue by troschi** [seife/meta-su980#2]
Hi,

can you tell me, for what this repository is useful?
Are those patches to build a kernel for the Golden Media Hypercube STB box?

Thanks!

Kind regards

**Comment by seife** [comment]
This is a yocto / openembedded meta layer to build an image for the GM hypercube box, to be used with meta-neutrino-mp.

It is unmaintained. It did never work well, because the hardware and especially the kernel drivers are utter crap.
